### PR TITLE
Move API to java classes with documentation

### PR DESCRIPTION
**Pull request by petterarvidsson**
Move all parts of the API into Java classes and properly document each class as it is moved. This will later on be broken out into it's own server-api project that can be be used by plugins instead of server.

### CODE REVIEW

**Comment by petterarvidsson** [comment]
@nsg Moved the first scala case class from API to a immutable Java class with documentation. I would like to apply this pattern to the whole API.

**Comment by nsg** [comment]
@petterarvidsson 

Looks good, like it! :+1:

**Comment by petterarvidsson** [comment]
@nsg Documented all of konstructs.api now. Took some time...

If you want to build it using javadoc (rather than scaladoc that will make a mess out of it) add the following line to build.sbt:
```
sources in (Compile, doc) <<= sources in (Compile, doc) map { _.filterNot(_.getName endsWith ".scala") }
```

Next would be documenting konstructs.api.messages and then updating KonstructsActor including better docs for it.

**Comment by nsg** [comment]
@petterarvidsson awesome!

**Pull request merged**
