### PR TITLE
Remove snow and sand gen from worldgen.

### PR DESCRIPTION
**Pull request by nsg**
@petterarvidsson this one I assume?

### CODE REVIEW

**Comment by petterarvidsson** [comment]
@nsg I have now tweaked the three plugins to generate what I think is a pretty cool world:
- Grass (based on your tweaks): https://github.com/konstructs/server-plugin-grass/pull/4
- Flowers: https://github.com/konstructs/server-plugin-flowers/pull/8
- Forest: https://github.com/konstructs/server-plugin-forest/pull/11

Dense forest are still very common, especially on the flatter areas, but there are now also more of grass lands. On higher altitude only the birch is growing (it grows in the snow, but can spread to the yellow grass).

Please try it out and tell me what you think.

**Comment by nsg** [comment]
@petterarvidsson Looking forward to test it,

I have read the code and it looks good, I will give it a try and see the result tomorrow.

**Comment by petterarvidsson** [comment]
I have made some updates to the PRs so be sure to run the latest version :-)

**Comment by nsg** [comment]
screenshot from 2016-05-16 20 16 16

@petterarvidsson Nice! :+1:

**Comment by petterarvidsson** [comment]
@nsg Let's merge this one as well, since the plugins now provide a superior world generation

**Comment by nsg** [comment]
@petterarvidsson agree!

**Pull request merged**
