### PR TITLE
Make l-system tailrecursive

### PR DESCRIPTION
**Pull request by petterarvidsson**
- This makes it possible to process much larger l-systems with many more
  iterations

### CODE REVIEW

**Comment by petterarvidsson** [comment]
@nsg This makes the l-system recursion into a loop eliminating the stack limit on it.

**Comment by petterarvidsson** [comment]
A tree with a couple of additional generations :-)

screenshot from 2016-01-23 22 11 53

**Comment by petterarvidsson** [comment]
Do you call that a tree? This is a tree:
screenshot from 2016-01-23 22 32 50

**Comment by nsg** [comment]
Lol, nice :+1:

**Comment by petterarvidsson** [comment]
@nsg I am done with this. I think I can not get much more simple speed ups now. It works well for trees up to very decent sizes.

**Comment by nsg** [comment]
@petterarvidsson :+1:

**Pull request merged**
