### PR TITLE
Fix make torches easy to destroy

### PR DESCRIPTION
**Pull request by petterarvidsson**

### CODE REVIEW

**Comment by petterarvidsson** [comment]
@nsg What do you think?

**Comment by petterarvidsson** [comment]
Since there is only one torch per block I would say it makes sense to keep it singular

**Comment by nsg** [comment]
Yeah, plural made sense because several different touches will be grouped under that class in the future.

**Comment by petterarvidsson** [comment]
I am more thinking in terms of "isa" relations. So that a class is something a block is, Just like in object oriented programming. I think it makes sense since classes are giving blocks properties.

**Comment by nsg** [comment]
okay!

**Pull request merged**
