### PR TITLE
Move filters to API and use them instead

### PR DESCRIPTION
**Pull request by petterarvidsson**

### CODE REVIEW

**Comment by petterarvidsson** [comment]
This is dependent on https://github.com/konstructs/server-api/pull/11 being merged and released.

**Comment by petterarvidsson** [comment]
@nsg This updates the server to behave according to the API published in https://github.com/konstructs/server-api/pull/11

**Comment by petterarvidsson** [comment]
@nsg this seems to work properly now. It also handles all cases of a plugin updating a block in the filter (either to be returned to the user or to be updated in the world). Very powerful stuff can be done with the tertiary filter now. Implementation wise a bit complicated, but at least it is now "hidden" behind the nice API.

**Comment by nsg** [comment]
@petterarvidsson yes, it looks good

**Pull request merged**
