### PR TITLE
Support for actions without position

### PR DESCRIPTION
**Pull request by petterarvidsson**

### CODE REVIEW

**Comment by petterarvidsson** [comment]
@nsg This adds the support for actions that didn't click a block

**Comment by petterarvidsson** [comment]
I guess we should also support the third button, now it crashes if it is sent

**Comment by nsg** [comment]
Okay, and yeah, 3rd button is probably a good idea :)

**Comment by petterarvidsson** [comment]
@nsg Now also with the tertiary action

**Comment by petterarvidsson** [comment]
hmm... seems to not work that great :-)

**Comment by nsg** [comment]
I guess I wait a little before I try it then :)

**Comment by petterarvidsson** [comment]
@nsg Hmm, I just managed to run the wrong version of the client. It seems to work as advertised :-)

**Comment by nsg** [comment]
Oh, all good then!

**Pull request merged**
