### PR TITLE
Add a NOTHING BlockFilter

### PR DESCRIPTION
**Pull request by petterarvidsson**
- This is the starting point for OR filters

### CODE REVIEW

**Comment by nsg** [comment]
@petterarvidsson Like that you also renamed EMPTY to the much more descriptive EVERYTHING.

**Comment by petterarvidsson** [comment]
Shall I merge?

**Comment by nsg** [comment]
@petterarvidsson mergy! merge! :+1:

**Comment by petterarvidsson** [comment]
Merged :wink:

**Pull request merged**
