### PR TITLE
Send events on ReplaceBlocks

### PR DESCRIPTION
**Pull request by nsg**
Added events to ReplaceBlocks.

### CODE REVIEW

**Comment by nsg** [comment]
@petterarvidsson what do you think, can we merge this? :)

**Comment by petterarvidsson** [comment]
@nsg I would change EventBlockUpdated to be EventBlockUpdated(blocks: Map[Position, BlockTypeId]) other than that I think it's a go!

**Comment by nsg** [comment]
@petterarvidsson what do you think about this?

**Comment by nsg** [comment]
Rebased on master, you can merge it, if you like it.

**Comment by petterarvidsson** [comment]
@nsg Looks awesome!

**Pull request merged**
