### PR TITLE
Server clean-up and implement EventBlock* events.

### PR DESCRIPTION
**Pull request by nsg**
* Various clean-ups
* Implement `EventBlockRemoved` and `EventBlockUpdated`, see: https://github.com/konstructs/server/pull/89#issuecomment-168556026
* Add Java `on*` functions to `KonstructsActor`

### CODE REVIEW

**Comment by petterarvidsson** [comment]
@nsg I think this looks awesome! The indentation is correct. I can add scalriformat tool to the build later on, but it would format just as you did.

**Comment by nsg** [comment]
Okay, I have not added to new events called `EventBlockRemoved` and `EventBlockUpdated`, if understand everything correctly they should get a copy of the block event when it's written to the database.

I placed the events under `PutBlockTo` and `RemoveBlockTo` and they do what I want ... not sure when `ReplaceBlockTo` is triggered ... need to figure that out :)

I'm successfully using this new API from "grass" with an configuration like this:

```
org/konstructs/block-manager {
  block-update-events {
    org/konstructs/grass = org/konstructs/grass
  }
}
```

And it work, my `onReceive` method outputs these nice messages:
```
got message: EventBlockRemoved(Position(-1,364,-3))
got message: EventBlockUpdated(Position(-1,364,-3),Block(None,BlockTypeId(org/konstructs,stone)))
```

**Comment by nsg** [comment]
@petterarvidsson what do you think? Crazy code or okay code? :)

If you like it I will add a few more events and then, I suggest a merge and a artefact that I can continue work against.

**Comment by petterarvidsson** [comment]
@nsg It is looking correct. The only drawback is that you are sending the events before they actually happen, so a query for e.g. the block that was put might not necessarily return data after the event has happened. The events "happen" in the shard actor when the data is overwritten. We can easily change this as we go to be sent from somewhere else, so let's just keep it simple for now.

Awesome work with all the clean-ups btw!

**Comment by nsg** [comment]
@petterarvidsson 

> The only drawback is that you are sending the events before they actually happen

I see, that's true. Not a problem for my use case. The idea with the `Event*` messages are a event message channel, not with a 100% guaranteed state anyway :)
But of course it would be nice to only send the message if the update/remove was really done, a future improvement :)

I added the last trigger and updated the Java function to include these new messages.

ready to be reviewed for a merge, and server release.

**Comment by petterarvidsson** [comment]
@nsg :+1: Super neat!

**Comment by nsg** [comment]
Nice, I will merge and release then!

**Pull request merged**
