### PR TITLE
Add gitter messages to bintray uploads.

### PR DESCRIPTION
**Pull request by nsg**

### CODE REVIEW

**Comment by nsg** [comment]
@petterarvidsson and for bintray

**Comment by petterarvidsson** [comment]
@nsg :+1: 

It would be cool if the URL to the build would be in the message. Is that possible?

**Comment by nsg** [comment]
I like to keep it short, but markdown is supported as well so maybe a markdown link to the build?

**Comment by petterarvidsson** [comment]
@nsg Yes. But thinking about it maybe it's sort of a pointless feature... who will download the server jar from a chat?

**Comment by nsg** [comment]
@petterarvidsson true :)

**Pull request merged**
