### PR TITLE
Use block damage for primary action

### PR DESCRIPTION
**Pull request by petterarvidsson**
- Let the block provided in the primary action act as a tool on the
  block pointed at
- Let both the tool block and the block pointed at receive damage
- Let the tool receive 10 times less damage
- If no tool is provided, let VACUUM ac as a tool

### CODE REVIEW

**Comment by nsg** [comment]
Looks good

**Comment by petterarvidsson** [comment]
@nsg I am adding a damage multiplier to block type to make things easier here. E.g. I guess it will be common that we want add a tool that deals extra damage to specific types of blocks. So I am adding the functionality that a block can have a damage multiplier for block types and block classes.

**Comment by nsg** [comment]
@petterarvidsson yup, that do sounds like a good idea. I like specialized tools.

**Comment by petterarvidsson** [comment]
https://github.com/konstructs/server-api/pull/8 <- that what it'll look like in the API

**Comment by petterarvidsson** [comment]
@nsg I am thinking of introducing two very basic tools into the core server: http://humanorigins.si.edu/evidence/behavior/stone-tools/early-stone-age-tools

The "Hammerstone" (for mining other stone) and the "Handaxe" for wood cutting. I think they will both look pretty decent as plants :-)

**Comment by nsg** [comment]
@petterarvidsson nice with stone age tools :+1:

**Comment by petterarvidsson** [comment]
I took this a bit further. Now one can define default values for block classes that will be "inherited" by block types. This makes it a lot easier to give uniform durability for different classes of blocks. I am also using the damage multipliers (which also can be defined in a class) when damaging blocks. I also added a "hammerstone" tool, which is the most basic tool that can speed up mining of stone and wood (which are the more heavy things to mine).

**Comment by petterarvidsson** [comment]
Related plugin PRs:
https://github.com/konstructs/server-plugin-forest/pull/15
https://github.com/konstructs/server-plugin-grass/pull/6
https://github.com/konstructs/server-plugin-flowers/pull/10

**Comment by petterarvidsson** [comment]
@nsg This is done now, but I'll take a look at it tomorrow night again before merging. I can run the server and destroy different blocks with different speed (also depending on the tool used) and the tool deteriorate with use (watch out so you don't destroy your tool sack!). When the client renders the damage I think this will look pretty awesome and add a lot of fun to the game.

**Comment by nsg** [comment]
@petterarvidsson nice, looking forward to test this.

**Comment by nsg** [comment]
... and yes, release 7 will be a good one!

**Comment by petterarvidsson** [comment]
last commit needs: https://github.com/konstructs/server-api/pull/9

**Comment by petterarvidsson** [comment]
@nsg This is done now. In general I think that we are ready for release 7 now!

**Pull request merged**
