### PR TITLE
Add convenience methods to konstructs actor bsae class

### PR DESCRIPTION
**Pull request by petterarvidsson**

### CODE REVIEW

**Comment by petterarvidsson** [comment]
@nsg While porting the forest plugin, I was lacking the following methods. I will move on with the flowers now and might add some more. Comments?

**Comment by nsg** [comment]
@petterarvidsson Looks good, common operations, I like it! I will start porting Grass my self soon, just some coffee and lunch before that :)

**Comment by petterarvidsson** [comment]
@nsg Porting flowers "required" one more method.

**Comment by nsg** [comment]
@petterarvidsson Looks good

**Pull request merged**
