### PR TITLE
Feature introduce block rotation

### PR DESCRIPTION
**Pull request by petterarvidsson**

### CODE REVIEW

**Comment by petterarvidsson** [comment]
This is dependent on the API changes in: https://github.com/konstructs/server-api/pull/13

**Comment by nsg** [comment]
Nice! `test.png` is amazing!

Finally a day with the time to read and understand your PR:s, looks good.

Just a minor thought, maybe increase the protocol version consider that we have changed the protocol?

**Comment by petterarvidsson** [comment]
@nsg Regarding the protocol version. I wanted to increase it on release time so that we don't have to increase it every time we change a protocol feature. There have been several other changes as well, some of them already merge. What do you think?

**Comment by nsg** [comment]
@petterarvidsson yeah, that's true. Sounds good.

**Pull request merged**
