### PR TITLE
Add Typesafe Config object as optional third arg

### PR DESCRIPTION
**Pull request by petterarvidsson**
- Extend the plugin loading code to accept also methods annotated with
  PluginConstructor that as a optional third argument takes a Typesafe
  Config object

### CODE REVIEW

**Comment by petterarvidsson** [comment]
@nsg This adds the possibility for a Plugin to get its entire config as an optional third argument to the plugin constructor method (the one that returns Props). I will update forest and flowers as examples.

**Comment by nsg** [comment]
@petterarvidsson I like it, easier (for me) to understand, so I like it!

**Comment by petterarvidsson** [comment]
Usage examples:
https://github.com/konstructs/server-plugin-flowers/pull/9
https://github.com/konstructs/server-plugin-forest/pull/14

**Comment by nsg** [comment]
@petterarvidsson yup, it was mainly these examples I was referring to :)

**Pull request merged**
